function harvest = configure_examples(filename, dataLines)
%IMPORTFILE Import data from a text file
%  HARVEST = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  HARVEST = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  harvest = importfile("/home/kaiobach/Research/hu_hu_hu/sprint28/bookkeeping_scidat_nomad_em_paper/harvest.examples.10.em.ang.unpack.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 29-Apr-2025 16:10:15

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 8);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["use", "atomtypes_hint", "main_file_data_original_path", "main_file_data_hashed", "main_file_meta_original_path", "main_file_meta_hashed", "main_file_data_byte_size", "main_file_meta_byte_size"];
opts.VariableTypes = ["double", "char", "char", "char", "char", "char", "double", "char"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["atomtypes_hint", "main_file_data_original_path", "main_file_data_hashed", "main_file_meta_original_path", "main_file_meta_hashed", "main_file_meta_byte_size"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["atomtypes_hint", "main_file_data_original_path", "main_file_data_hashed", "main_file_meta_original_path", "main_file_meta_hashed", "main_file_meta_byte_size"], "EmptyFieldRule", "auto");

% Import the data
harvest = readtable(filename, opts);

end